name: GNG packaging

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Package
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args: './bin ./gradle ./lib'
          fpm_opts: '--debug -n gng -t deb -s dir'
